In [ ]:
#random integer values
from numpy.random import seed
from numpy.random import randint
 
values = randint(1,20,20)
print(values)

[10  4  8  5  6  7  9  1  3 11 16 16  8 11 15  1  2 18 14  4]


In [ ]:
#Random Numbers
from numpy.random import seed
from numpy.random import rand
seed(10)
print(rand(3))
seed(1)
print(rand(3))
seed(3)
print(rand(3))


[0.51082761 0.89294695 0.89629309]
[4.17022005e-01 7.20324493e-01 1.14374817e-04]
[0.5507979  0.70814782 0.29090474]


In [ ]:
#Shuffled Array
from numpy.random import seed
from numpy.random import shuffle
seed(1)
sequence = [i for i in range(70)]
print(sequence)
shuffle(sequence)
print(sequence)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69]
[65, 26, 66, 54, 27, 60, 49, 36, 48, 31, 2, 39, 53, 35, 43, 57, 62, 52, 55, 47, 51, 34, 21, 59, 3, 38, 33, 58, 10, 15, 19, 40, 24, 8, 17, 0, 63, 44, 61, 67, 13, 22, 32, 30, 41, 46, 23, 4, 14, 29, 28, 42, 11, 56, 18, 69, 20, 50, 25, 6, 45, 7, 68, 1, 16, 64, 5, 9, 12, 37]
